### ISSUE TITLE
How do you insert an EOL?

### ISSUE THREAD

**Issue by nunmap** [inkarkat/vim-ModelineCommands#1]
Hi inkarkat, 
Firstly, really useful plugin, thank you for making it.

I have an `autocmd` that inserts some text and puts the cursor in a specific position every time a file in opened.

```autocmd BufRead somefile execute "normal 2Gi#\t\tsometext\<cr>\<esc>2G2|"```

Is it possible to put this into the file in question?

This works without inserting a new line:
```# vimcommand:normal 2Gi#		sometext2G2|:```
That  is an escape (ascii dec 27)

But how do I get the new line? I've tried line feed (ascii dec 10) but to no avail. I'm using unix `'fileformat'`.

**Comment by inkarkat** [comment]
You can simply use `:execute` to be able to use the special notations (`\<CR>`; `\n` would also work):

    # vimcommand:execute "normal 2Gi#\t\tsometext\<cr>\<esc>2G2|":

To insert a line, I would probably prefer `:put` with a string expression:

    :1put =\"#\tsometext\"

Or the low-level `append()` function:

    :call append(1, "#\tsometext")

---

The cursor positioning may or may not work - many users have some sort of autocmd configuration that automatically restores the last cursor position when opening a file, and as the plugin is not triggered exactly like your `:autocmd`, the order of execution may be different and prevent cursor positioning from within a modeline command. This could be worked around by using `:call feedkeys(...)` instead of `:normal`.

**Comment by nunmap** [comment]
Thank you for your thorough & detailed response. I didn't have any success simply using `:execute` with the special notations. However I was able go get it working using the other methods described and learnt a bit more about Vim in the process.

Please except this virtual cookie.
![Cookie](https://upload.wikimedia.org/wikipedia/commons/b/b4/Choco_chip_cookie.png)
